apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image2 }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              sprotocol: TCP