apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: secret-name
      data:
        - key: username
          objectName: secret-username
        - key: password
          objectName: secret-password


apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "aws-secrets"
  containers:
    - name: container
      image: image
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
#retrieve as /mnt/secrets-store/username
